[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dust3r"
version = "1.0.0"
description = "DUSt3R: Geometric 3D Vision Made Easy"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[tool.setuptools.packages.find]
where = ["."]
include = ["dust3r*", "croco*"]
